# Generated by Django 4.2.7 on 2024-11-04 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_user_age_alter_user_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='additional_info',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='interests',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
