# Generated by Django 4.2.7 on 2024-11-11 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0006_chatgroup_created_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatgroup',
            name='description',
            field=models.TextField(max_length=255),
        ),
    ]
