# Generated by Django 4.2.7 on 2024-11-11 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0007_alter_chatgroup_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatgroup',
            name='description',
            field=models.TextField(blank=True, max_length=255),
        ),
    ]
