# Generated by Django 4.2.7 on 2024-11-24 09:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0008_alter_chatgroup_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chatmessage',
            old_name='message',
            new_name='encrypted_message',
        ),
    ]
